spring.application.name=Real-timeLeader
spring.data.redis.host=redis-17564.c13.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=17564
spring.data.redis.password=Ci1vmDNV5nqskNIQ7DfHjaXs0hmQqH8M
# Make sure this is NOT 'none'
spring.main.web-application-type=servlet
# H2 Database Config (for User Auth)
spring.datasource.url=jdbc:h2:mem:leaderboard_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# Server Settings
server.port=8081
